// Haven desktop i18n — a plain-script dictionary + t() helper, loaded BEFORE app.js
// (see index.html). No build step, no framework: it defines globals the app module reads.
//
// Languages are EXACTLY six (ja, de, es, ko, pt-BR, it) plus the English source — an export
// compliance constraint, not a preference (see loc-glossary.json at the repo root): Haven cannot
// ship into France or China, so no fr and no zh, ever. "Haven", "Circle" (the product noun),
// "Relay", "Kyber" and "Dilithium" are never translated.
//
// Placeholders are {0}/{1}/… positional, substituted by t(key, ...args).
// GENERATED from tooling-side JSON dictionaries — edit values here AND keep en in sync if you
// touch strings by hand.
(function () {
  "use strict";

  const EN = {
    "just_now": "just now",
    "close": "Close",
    "cancel": "Cancel",
    "save": "Save",
    "done": "Done",
    "add": "Add",
    "remove": "Remove",
    "delete": "Delete",
    "rename": "Rename",
    "create": "Create",
    "copy": "Copy",
    "you": "You",
    "someone": "Someone",
    "retry": "Retry",
    "saved": "Saved",
    "attach": "Attach",
    "send": "Send",
    "accept": "Accept",
    "approve": "Approve",
    "dismiss": "Dismiss",
    "edit": "Edit",
    "report": "Report",
    "back": "Back",
    "more": "More",
    "settings": "Settings",
    "messages": "Messages",
    "activity": "Activity",
    "close_window": "Close window",
    "minimize_window": "Minimize window",
    "zoom_window": "Zoom window",
    "manage_circle": "Manage circle",
    "new_message": "New message",
    "my_circle": "My Circle",
    "video_still_loading": "Video still loading…",
    "still_loading": "Still loading…",
    "not_available_yet": "Not available yet",
    "downloading": "Downloading…",
    "no_longer_available": "No longer available",
    "tell_when_back": "We'll tell you when it's back",
    "ask_for_it_back": "Ask for it back",
    "download_size": "Download {0}",
    "removed_to_save_space": "Removed to save space",
    "hide_hidden_posts": "Hide hidden posts",
    "show_hidden_posts": "Show hidden posts ({0})",
    "new_circle_menu": "New circle…",
    "reacted": "Reacted {0}",
    "commented": "Commented",
    "voted": "Voted",
    "shared_a_story": "Shared a story",
    "messaged_the_group": "Messaged the group",
    "sent_you_a_message": "Sent you a message",
    "posted_verb": "Posted",
    "nothing_yet": "Nothing yet",
    "activity_empty_sub": "Reactions, comments, new posts and messages land here.",
    "show_older": "Show older",
    "show_older_left": "Show older · {0} left",
    "offline_posts_sync": "Offline — posts sync when you reconnect",
    "internet": "internet",
    "relaying_here": "relaying here",
    "online_looking": "Online — looking for your circle…",
    "connected": "Connected",
    "offline": "Offline",
    "link_circle_not_in": "That link points at a circle you're not in.",
    "convo_not_on_device": "That conversation isn't on this device yet.",
    "post_circle_not_in": "That post is in a circle you're not in.",
    "post_not_reached": "That post hasn't reached this device yet, or it isn't in this circle.",
    "post_was_unsent": "That post was unsent.",
    "link_points_story": "That link points at a story — open it under Stories.",
    "give_circle_relay": "Give this circle a relay",
    "relay_nudge_sub": "A few of you are here now — a relay holds your sealed posts so nobody has to be online at the same time.",
    "set_up_relay": "Set up a relay",
    "wt_nobody_online_t": "Nobody has to be online at once",
    "wt_nobody_online_b": "Posts upload sealed; friends pick them up next time they open Haven.",
    "wt_media_t": "Photos and videos actually arrive",
    "wt_media_b": "Media comes from the relay, not the poster's device, so it lands even when they're offline.",
    "wt_routes_t": "It routes around home routers",
    "wt_routes_b": "When devices can't reach each other directly, the relay forwards sealed messages — no port forwarding.",
    "wt_cant_read_t": "The relay can't read a thing",
    "wt_cant_read_b": "It only ever holds sealed blobs and a routing header — no content key ever goes near it. ",
    "learn_more": "Learn more",
    "wt_how_heading": "How to set one up",
    "wt_easy_t": "The easy way — this PC",
    "wt_easy_b": "One click: this PC holds the circle's sealed mailbox — turn on the two Relay toggles to survive reboots.",
    "wt_headless_t": "Or with no window at all",
    "wt_headless_b": "Prefer no window? Run haven-desktop --headless for relay-only.",
    "wt_spare_t": "Or a spare machine",
    "wt_spare_b": "On a Mac, Linux box, or Raspberry Pi:\ncurl -fsSL https://wemiller.com/apps/haven/relay/install.sh | sh\n\nOn Windows, in PowerShell:\nirm https://wemiller.com/apps/haven/relay/install.ps1 | iex\n\nIt sets itself to start on every reboot; paste its node id under Relay to adopt it.",
    "wt_counton_heading": "What everyone in the circle can count on",
    "wt_only_t": "Only the people you added can read it",
    "wt_only_b": "Everything you post is sealed on this PC to your circle's members. Remove someone and the circle's key rotates, so they can't read anything posted afterwards.",
    "wt_pq_t": "Encrypted for the long haul",
    "wt_pq_b": "Double-locked: today's proven encryption plus post-quantum. Keys never leave your devices. ",
    "use_pc_as_relay": "Use this PC as the relay",
    "add_relay_running": "Add a relay I'm running →",
    "not_now": "Not now",
    "pc_now_relay": "This PC is now the relay",
    "mute_all_videos": "Mute all videos",
    "unmute_all_videos": "Unmute all videos",
    "nothing_here_yet": "Nothing here yet",
    "feed_empty_sub": "Share your first moment below. As your circle connects, their posts show up here too.",
    "share_something": "Share something…",
    "connection_request_one": "1 connection request",
    "connection_requests_many": "{0} connection requests",
    "click_to_review": "Click to review who wants to connect",
    "upgrade_this_circle": "Upgrade this circle",
    "upgrade_circle_sub": "If you made this circle, give it a verified owner so removing someone cuts them off for good. Everyone here chooses whether to follow you.",
    "upgrade": "Upgrade",
    "is_upgrading": "{0} is upgrading “{1}”",
    "follow_upgrade_sub": "They say they made this circle. We can't check that, so only follow if that's right — whoever you follow will be able to remove people.",
    "follow": "Follow",
    "add_to_your_story": "Add to your story",
    "disappears_label": "Disappears: {0}",
    "video_muted": "🔇 Video muted",
    "mute_video": "🔊 Mute video",
    "device_only": "Device only",
    "syncing": "Syncing",
    "posted_toast": "Posted",
    "write_something_first": "Write something first",
    "scheduled_toast": "Scheduled",
    "photo_or_video": "Photo or Video",
    "camera": "Camera",
    "voice": "Voice",
    "add_a_song": "Add a song",
    "disappears_after": "Disappears after…",
    "off": "Off",
    "one_hour": "1 hour",
    "one_day": "1 day",
    "one_week": "1 week",
    "send_later": "Send later…",
    "post_btn": "Post",
    "paste_song_link": "Paste a song link (Apple Music, Spotify, YouTube…)",
    "song_title_ph": "Title",
    "artist_ph": "Artist",
    "attach_a_song": "Attach a song",
    "song_link_hint": "The link opens in your friend's own music app.",
    "add_link_and_title": "Add a link and a title",
    "unknown_artist": "Unknown artist",
    "unknown_song": "Unknown song",
    "open_in_maps": "Open in maps",
    "sensitive_content": "Sensitive Content",
    "tap_to_view": "Tap to view",
    "attachment_chip": "Attachment",
    "tap_to_reveal": "🔒 Tap to reveal",
    "that_file": "That file",
    "videos_word": "videos",
    "photos_word": "photos",
    "file_too_large": "{0} is {1} — Haven caps {2} at {3}, so it wasn't attached.",
    "video_word": "video",
    "photo_word": "photo",
    "over_limit": "That {0} is over Haven's {1} limit, so it wasn't attached.",
    "couldnt_attach_file": "Couldn't attach that file",
    "tap_record_to_start": "Tap record to start",
    "record_btn": "● Record",
    "stop_attach": "■ Stop & attach",
    "mic_unavailable": "Mic unavailable: {0}",
    "recording": "Recording…",
    "voice_note_cap": "Voice notes are capped at {0} minutes.",
    "couldnt_save": "Couldn't save: {0}",
    "voice_message": "🎙️ Voice message",
    "filter_original": "Original",
    "filter_warmth": "Warmth",
    "filter_cool": "Cool",
    "filter_sepia": "Sepia",
    "filter_noir": "Noir",
    "filter_vivid": "Vivid",
    "capture_failed": "Capture failed: {0}",
    "capture_btn": "📸 Capture",
    "stop_btn": "■ Stop",
    "save_failed": "Save failed: {0}",
    "clip_cap": "Clips are capped at {0} minutes.",
    "record_video_btn": "🎥 Record",
    "camera_title": "📷 Camera",
    "camera_unavailable": "Camera unavailable: {0}",
    "schedule_title": "🕓 Schedule",
    "schedule_hint": "Haven has no server, so a scheduled message sends while this app is running at that time.",
    "pick_future_time": "Pick a future time",
    "schedule_btn": "Schedule",
    "couldnt_attach": "Couldn't attach: {0}",
    "video_cant_strip": "This video can't be stripped of location data on this system, so it wasn't attached.",
    "video_meta_failed": "Couldn't process this video's metadata, so it wasn't attached.",
    "video_too_long": "That video is {0} minutes — Haven caps videos at {1}, so it wasn't attached.",
    "video_finish_failed": "Couldn't finish processing this video, so it wasn't attached.",
    "couldnt_check_media": "Couldn't check your media: {0}",
    "stopped_no_space": "Stopped — not enough free space to re-encode safely.",
    "couldnt_reshare": "Some posts couldn't be re-shared: {0}",
    "nothing_smaller": "Nothing could be made smaller",
    "item_one": "1 item",
    "items_many": "{0} items",
    "post_one": "1 post",
    "posts_many": "{0} posts",
    "reoptimize_summary": "{0} re-shared across {1} · {2} → {3} ({4}% smaller)",
    "stopped": "Stopped.",
    "checking_shared_media": "Checking your shared media…",
    "reoptimizing_of": "Re-optimizing {0} of {1}…",
    "reoptimize_title": "Re-optimize media I already shared",
    "photo_one": "1 photo",
    "photos_many": "{0} photos",
    "shrink_reshare": "Shrink & re-share {0}",
    "found_text": "{0} · {1} currently on every member's device",
    "legacy_suffix": " · {0} shared before Haven learned to compress",
    "batch_suffix": ". This run does the {0} largest; click again for the rest.",
    "stopping": "Stopping…",
    "stop_after_this": "Stop after this one",
    "all_photos_small": "Every photo you've shared is already as small as it can be.",
    "videos_skipped": "{0} video(s) and voice note(s) of yours ({1}) skipped — video re-encoding isn't available here; use Haven on your phone for those.",
    "no_copy_yet": "No copy yet",
    "all_copies": "All",
    "n_of_m": "{0} of {1}",
    "on_this_device_suffix": "{0} · on this device",
    "not_on_any_relay": "Not on any relay yet",
    "where_stored": "Where this is stored",
    "attachment_one": "1 attachment",
    "attachments_many": "{0} attachments",
    "stranded_warning": "Only this device's own relay has a copy, so nobody else can fetch it yet.",
    "edited_suffix": " · edited",
    "post_unsent_tombstone": "🚫 This post was unsent",
    "open_in_music_app": "Open in your music app",
    "remove_reaction": "Remove your reaction",
    "react": "React",
    "react_emoji": "React {0}",
    "more_reactions": "More reactions",
    "comments": "Comments",
    "add_a_reply": "Add a reply…",
    "attach_reply_phone": "Attach a photo to a reply from the phone apps for now",
    "send_reply": "Send reply",
    "report_harassment": "Harassment or bullying",
    "report_nudity": "Nudity or sexual content",
    "report_violence": "Violence or dangerous acts",
    "report_spam": "Spam or scam",
    "report_other": "Something else",
    "reported_toast": "Reported",
    "report_note_ph": "Add a note for your circle (optional)",
    "report_post": "Report post",
    "whats_wrong": "What's wrong with it?",
    "also_block": "Also block {0}",
    "report_hint": "Hides the post for you now; your circle sees the report. Nothing is ever logged.",
    "reported_by": "Reported by {0}",
    "act": "Act",
    "reported_post": "Reported post",
    "hide_for_me": "Hide for me",
    "remove_confirm": "Remove {0} from this circle? Their posts leave your view of the circle and they can't rejoin through you.",
    "removed_toast": "Removed",
    "remove_from_circle_btn": "Remove {0} from circle",
    "blocked_toast": "Blocked",
    "block_person": "Block {0}",
    "keep_on_device": "Keep on this device",
    "kept_on_device": "Kept on this device",
    "couldnt_keep": "Couldn't keep: {0}",
    "share_post": "Share post",
    "link_copied": "Link copied",
    "couldnt_copy": "Couldn't copy: {0}",
    "unsend": "Unsend",
    "unsent_toast": "Unsent",
    "hide": "Hide",
    "unhide": "Unhide",
    "message_name": "Message {0}",
    "couldnt_open_message": "Couldn't open the message",
    "edit_post": "Edit post",
    "circle_name_ph": "Circle name (e.g. Family)",
    "new_circle": "New circle",
    "your_name_for_circle_ph": "Your name for this circle",
    "no_contacts_connect_first": "No contacts yet — connect a friend first.",
    "added_check": "Added ✓",
    "added_name": "Added {0}",
    "couldnt_add": "Couldn't add: {0}",
    "circle_admin": "Circle admin",
    "admin_check": "Admin ✓",
    "make_admin_title": "Make this member an admin (can remove members)",
    "now_admin": "{0} is now an admin",
    "only_creator_promote": "Only the circle's creator or an admin can promote members",
    "couldnt_promote": "Couldn't promote: {0}",
    "make_admin": "Make admin",
    "remove_from_my_circle": "Remove from My Circle",
    "remove_from_this_circle": "Remove from this circle",
    "removed_check": "Removed ✓",
    "removed_name": "Removed {0}",
    "couldnt_remove": "Couldn't remove: {0}",
    "no_relays_configured": "No relays configured yet.",
    "default_all_circles_suffix": " — default (all circles)",
    "updated_toast": "Updated",
    "manage_relays_link": "Manage relays →",
    "invite_someone": "Invite someone to this circle",
    "name_label": "Name",
    "renamed_toast": "Renamed",
    "circle_name_hint": "What this circle is called for you and everyone in it.",
    "your_name_label": "Your name",
    "saved_only_you": "Saved — only you see this",
    "using_circles_own_name": "Using the circle's own name",
    "nickname_hint": "Only you see this. It never reaches anyone else in the circle, and it doesn't change the circle's name for them. Leave it empty to use the circle's own name.",
    "relays_for_circle": "Relays for this circle",
    "relays_for_circle_hint": "Pick which of your relays carry this circle — the default relay always applies.",
    "members_label": "Members",
    "left_circle_toast": "Left circle",
    "leave_this_circle": "Leave this circle",
    "caption_your_story": "Caption your story…",
    "preview": "Preview",
    "song_plays": "🎵 Song plays",
    "clip_sound_on": "🔊 Clip sound on",
    "clip_sound_off": "🔇 Clip sound off",
    "song_soundtrack_title": "The attached song is this story's soundtrack — remove it to hear the clip",
    "hear_clip_title": "Hear the clip while you caption it",
    "style_plain": "Plain",
    "style_glow": "Glow",
    "style_shadow": "Shadow",
    "style_neon": "Neon",
    "style_highlight": "Highlight",
    "caption_color": "Caption color",
    "caption_style": "Caption style",
    "caption_font": "Caption font",
    "size_label": "Size",
    "undo_framing_title": "Undo zoom, pan and rotation",
    "reset_framing": "↺ Reset framing",
    "new_story": "New story",
    "story_hint": "Add a photo or video with the + button. Stories disappear after 24 hours.",
    "story_gestures_hint": "Drag to place the caption · scroll or pinch to zoom · shift-scroll to rotate · ⌥-drag to move the photo",
    "story_viewer_hint": "Tap to advance · ← → skip person · swipe to skip",
    "kept": "Kept",
    "keep": "Keep",
    "kept_on_profile": "Kept on your profile",
    "keep_on_profile": "Keep on your profile",
    "couldnt_update_keep": "Couldn't update Keep.",
    "whose_story": "{0}'s story",
    "delete_convo_confirm": "Delete conversation with \"{0}\"? Its local messages are cleared.",
    "secret_message_preview": "🔒 Secret message",
    "no_messages_yet": "No messages yet",
    "messages_empty_sub": "Use the compose button to start one.",
    "unpin": "Unpin",
    "pin": "Pin",
    "pin_limit": "You can pin up to 6 conversations.",
    "start": "Start",
    "start_group": "Start group",
    "new_group_n": "New group · {0}",
    "no_contacts_invite_first": "No contacts yet — invite someone from your circle first.",
    "message_unsent": "Message unsent",
    "edited": "edited",
    "editing_message": "Editing message",
    "disappears_after_label": "Disappears after {0}",
    "message_ph": "Message…",
    "secret_message_ph": "Secret message…",
    "voice_message_menu": "Voice message",
    "secret_on": "Secret: on",
    "send_secretly": "Send secretly",
    "dont_disappear": "Don't disappear",
    "after_1_hour": "After 1 hour",
    "after_1_day": "After 1 day",
    "after_1_week": "After 1 week",
    "audio_call": "Audio call",
    "video_call": "Video call",
    "more_reactions_menu": "More reactions…",
    "qr_unavailable": "QR unavailable",
    "your_invite": "Your invite",
    "your_invite_hint": "Have a friend scan this, or send them the link. Verify the safety code matches on both devices.",
    "invite_copied": "Invite copied",
    "copy_haven_link": "Copy haven:// link",
    "web_link_copied": "Web link copied",
    "copy_web_link": "Copy web link",
    "paste_invite_ph": "Paste a haven:// or https:// invite or post link…",
    "connect_friend": "Connect a friend",
    "invite_sent": "Invite sent — they'll appear once they accept",
    "not_haven_link": "That doesn't look like a Haven link",
    "connect": "Connect",
    "scan_qr_camera": "📷 Scan a QR with your camera",
    "requests_n": "Requests ({0})",
    "no_pending_requests": "No pending requests.",
    "safety_prefix": "safety: ",
    "ignore": "Ignore",
    "contacts_n": "Contacts ({0})",
    "no_contacts_yet": "No contacts yet.",
    "message_btn": "Message",
    "point_camera_qr": "Point your camera at a Haven QR code.",
    "scan_qr": "Scan QR",
    "invite_sent_short": "Invite sent!",
    "not_haven_qr": "Not a Haven QR",
    "days_7": "7 days",
    "days_30": "30 days",
    "days_90": "90 days",
    "months_6": "6 months",
    "year_1": "1 year",
    "no_limit": "No limit",
    "never": "Never",
    "keep_media_for": "Keep media for",
    "media_storage_limit": "Media storage limit",
    "saved_applies_next": "Saved — applies next time the relay starts",
    "relay_limits_hint_hosting": "Changes apply next time the relay starts — Stop hosting and start again to apply them now. Whichever limit is reached first wins: old media is swept on age, and the oldest goes first if the size cap is hit. Your circles' undelivered messages are never swept — only media.",
    "relay_limits_hint": "Whichever limit is reached first wins: old media is swept on age, and the oldest goes first if the size cap is hit. Your circles' undelivered messages are never swept — only media.",
    "adopt_ph": "Paste node id (64 hex) or haven-relay interface JSON…",
    "derp_ph": "optional — https://derp.example.com (sibling host for :3340)",
    "token_ph": "Cloudflare tunnel install token",
    "mode_auto_label": "Free trycloudflare",
    "mode_auto_hint": "A free temporary Cloudflare address — zero setup, but it changes every restart.",
    "mode_bundled_label": "Custom domain (Haven runs cloudflared)",
    "mode_bundled_hint": "Your own domain: paste it plus a Cloudflare tunnel token, and Haven runs the tunnel for you.",
    "mode_manual_label": "Manual / external tunnel",
    "mode_manual_hint": "You run the tunnel or reverse proxy; Haven just announces its HTTPS address.",
    "derp_label": "DERP fabric URL (optional, distinct from media)",
    "url_ph_auto": "optional stable media URL (switches to manual when set alone)",
    "saved_restart_hosting": "Saved — restart hosting to apply front-door settings",
    "public_front_door": "Public HTTPS front door",
    "front_door_hint": "Friends off your LAN need HTTPS to the media port (8674) and (for circle-hosted NAT fabric) DERP on 3340. Blobs stay E2E-sealed — the front door only moves ciphertext.",
    "media_public_url": "Media public URL",
    "tunnel_token_label": "Tunnel token (bundled mode only)",
    "save_front_door": "Save front door",
    "front_door_sealed": "Whichever mode you pick, the front door only ever carries sealed data. ",
    "live_tunnel": "Live Cloudflare tunnel",
    "live_tunnel_path": "One cloudflared → path proxy :8675 (media + DERP)",
    "url_copied": "URL copied",
    "live_tunnels_dual": "Live Cloudflare tunnels (dual)",
    "dual_hint": "Path proxy off — two free trycloudflare origins (both visible):",
    "media_label": "Media",
    "derp_fabric": "DERP fabric",
    "host_relay_pc": "Host the relay on this PC",
    "host_relay_hint": "Your circle's relay runs here so posts and media reach friends even when you're both offline. The relay never sees your content — everything is end-to-end sealed.",
    "relaying_status": "● Relaying",
    "relay_id_copied": "Relay id copied",
    "share_relay_id_hint": "Share this id with your circle so they adopt the same relay.",
    "stop_hosting": "Stop hosting",
    "start_hosting": "Start hosting",
    "relay_started": "Relay started",
    "configured_relays": "Configured relays ({0})",
    "configured_relays_hint": "Add more than one for redundancy — posts and media are mirrored to every relay, and if one goes down Haven quietly uses the others. The default relay (★) is inherited by every circle that hasn't picked its own. Removing a relay DEACTIVATES it (its name + circle settings survive so you can turn it back on); an inactive relay unseen for a week is cleaned up automatically.",
    "deactivated_config_kept": "deactivated — config kept",
    "s3_saf": "S3 · store-and-forward",
    "this_pc": "this PC",
    "reachable": "reachable",
    "retrying": "retrying…",
    "deactivate_title": "Stop using this relay (keeps config)",
    "relay_deactivated": "Relay deactivated",
    "deactivate": "Deactivate",
    "reactivate": "Reactivate",
    "relay_reactivated": "Relay reactivated",
    "unset_default_title": "Stop being the all-circles default",
    "unset_default": "Unset default",
    "make_default_title": "Use for every circle by default",
    "default_relay_set": "Default relay set",
    "make_default": "Make default",
    "relay_name_prompt": "Relay name",
    "erase_title": "Erase config for good",
    "relay_deleted": "Relay deleted",
    "star_default": "★ default",
    "default_for_all": "Default for all circles",
    "no_relays_yet": "No relays yet — host one above, adopt a friend's, or add an S3 bucket below.",
    "deleted_relays": "Deleted relays · {0}",
    "circles_count": " · {0} circle(s)",
    "restore": "Restore",
    "relay_restored": "Relay restored",
    "forget": "Forget",
    "restore_hint": "Restore puts a deleted relay back in the circles it served. Cleared after 30 days.",
    "relay_added": "Relay added",
    "paste_node_id_error": "Paste a 64-hex node id or the JSON block from haven-relay",
    "add_haven_relay": "Add Haven relay",
    "always_on_relay": "Always-on relay (survives reboot)",
    "always_on_hint": "Have Haven start automatically when you log in and keep hosting your circle's relay — so this PC stays a relay across reboots, no terminal needed.",
    "start_on_login": "Start Haven when I log in",
    "host_on_launch": "Host the relay automatically on launch",
    "run_headless": "Run headless",
    "headless_hint_html": "Prefer no window? Run <span class='mono'>haven-desktop --headless</span> for relay-only.",
    "name_optional_ph": "Name (optional)",
    "endpoint_ph": "Endpoint, e.g. https://s3.us-east-1.amazonaws.com",
    "region_ph": "Region",
    "bucket_ph": "Bucket name",
    "access_key_ph": "Access key id",
    "stored_keychain_ph": "•••••• (stored in your keychain)",
    "secret_key_ph": "Secret access key",
    "prefix_ph": "Key prefix (optional)",
    "make_default_all": "Make the default for all circles",
    "add_s3_title": "Add an S3 bucket as a relay (S3 / R2 / B2)",
    "byo_bucket": "Bring your own bucket as a store-and-forward relay. ",
    "configured_prefix": "✓ Configured: ",
    "not_configured": "Not configured.",
    "s3_warning": "⚠︎ Store-and-forward only: an S3 bucket holds sealed posts & media for offline delivery — it is NOT a live P2P relay (no realtime fan-out). The provider never sees plaintext; your secret stays in this device's keychain, never on any server. Works with AWS S3, Cloudflare R2, Backblaze B2, MinIO.",
    "s3_added": "S3 relay added",
    "update_bucket": "Update bucket",
    "add_s3_relay": "Add S3 relay",
    "s3_removed": "S3 relay removed",
    "relays": "Relays",
    "edit_profile": "Edit profile",
    "profile_private_hint": "This is just for the people you choose.",
    "your_stories": "Your stories",
    "your_posts_here": "Your posts show up here",
    "your_posts_sub": "Everything you share lives here — and a copy stays on your device.",
    "your_name_ph": "Your name",
    "bio_ph": "Add a short bio",
    "link_ph": "Add a link (e.g. yoursite.com)",
    "not_an_image": "That file isn't an image Haven can read",
    "change_photo": "Change photo",
    "add_photo": "Add photo",
    "add_a_photo": "Add a photo",
    "bio_hint": "Your bio and link show on your profile for the people in your circle.",
    "emoji_if_remove": "Emoji (used if you remove your photo)",
    "pick_emoji": "Pick an emoji",
    "profile_saved": "Profile saved & shared",
    "circle_private_title": "Your circle is private",
    "circle_private_sub": "Everything you share is locked so only your people can see it. No ads, no tracking — ever.",
    "relays_foot": "Manage where your circles' sealed posts & media live so they reach people who were offline. Add unlimited relays (a Haven node or your own S3 bucket), pick a default for every circle, and activate or deactivate each. Each circle can override the default in its own settings.",
    "blocked_people": "Blocked people",
    "blocked_foot": "People you've blocked can't see your posts or reach you. Unblock anyone here.",
    "identities": "Identities",
    "identities_foot": "Keep more than one identity on this PC and switch between them. Each has its own profile, circles and contacts.",
    "devices": "Devices",
    "devices_foot": "Link your other devices — each gets its own revocable key, never your master key.",
    "scheduled_messages": "Scheduled messages",
    "scheduled_foot": "Posts and DMs waiting to send. Compose one with the + menu's “Send later…”.",
    "privacy_media": "Privacy & media",
    "privacy_media_foot": "Notification lock-screen previews, super data saver, and whether to also send camera originals.",
    "appearance": "Appearance",
    "light": "Light",
    "dark": "Dark",
    "advanced": "Advanced",
    "advanced_foot": "Technical details, your identity, and starting over.",
    "also_send_original": "Also send original",
    "super_data_saver": "Super data saver",
    "privacy_toggles_foot": "Super data saver skips autoplay and prefers poster stills. “Also send original” keeps the camera file beside the optimized video.",
    "notification_previews": "Notification previews",
    "notification_previews_hint": "How much detail banners show on the lock screen (iOS/Android parity).",
    "full_previews": "Full previews",
    "name_type_only": "Name and type only",
    "minimal": "Minimal",
    "no_one_blocked": "No one is blocked.",
    "unblock": "Unblock",
    "nothing_scheduled": "Nothing scheduled. Use the composer's + menu ▸ “Send later…”.",
    "dm_label": "DM",
    "post_label": "Post",
    "attachments_count": "{0} attachment(s)",
    "sends_at": "sends {0}",
    "scheduled_title": "Scheduled",
    "measuring": "Measuring…",
    "remove_n_frees": "Remove {0} · frees {1}",
    "removing": "Removing…",
    "freed": "Freed {0}",
    "not_linked_any_post": "Not linked to any post",
    "kept_suffix": " · Kept",
    "unkeep": "Unkeep",
    "no_cached_media": "No cached media.",
    "nothing_stored_yet": "Nothing stored on this device yet.",
    "items_summary": "{0} · {1}",
    "kept_bytes": " · {0} kept",
    "manage_media": "Manage media",
    "manage_media_hint": "Sorted by size. Removing an item frees only the copy on this device — the post stays and can be re-downloaded. “Keep” exempts an item from every cleanup.",
    "security": "Security",
    "security_hint": "Run the on-device hybrid post-quantum self-test (Ed25519 + ML-DSA, X25519 + ML-KEM-768).",
    "run_self_test": "Run self-test",
    "all_checks_passed": "✅ All checks passed",
    "some_checks_failed": "⚠️ Some checks failed",
    "identity_label": "Identity",
    "hybrid_kem": "Hybrid KEM",
    "signatures": "Signatures",
    "reach_me_link": "Reach-me link",
    "storage": "Storage",
    "storage_hint": "Photos and videos from your circles, cached on this device. Manage them by size, set automatic limits, or clear media nothing references.",
    "n_kept": "{0} kept",
    "delete_older_than": "Delete local media older than",
    "keep_under": "Keep local media under",
    "auto_remove_hint": "Automatically remove old/excess cached media (oldest first) to stay under your caps — posts stay and re-download on demand. Kept items are never removed.",
    "cleaning_up": "Cleaning up…",
    "nothing_to_cleanup": "Nothing to clean up.",
    "file_one": "1 file",
    "files_many": "{0} files",
    "freed_across": "Freed {0} across {1}.",
    "cleanup_failed": "Cleanup failed: {0}",
    "cleanup_unused": "Clean up unused media",
    "start_over": "Start over",
    "start_over_hint": "Wipe this device's identity, contacts, circles and media. This cannot be undone.",
    "start_over_q": "Start over?",
    "start_over_confirm": "This permanently deletes your identity and all local data on this PC.",
    "delete_everything": "Delete everything",
    "this_device": "This device",
    "pass": "✓ pass",
    "fail": "✗ fail",
    "active_tag": "active",
    "switch_identity_confirm": "Switch to \"{0}\"? Haven will relaunch.",
    "switch_btn": "Switch",
    "rename_identity": "Rename identity",
    "remove_identity_confirm": "Remove \"{0}\" from this PC? Its local data is deleted.",
    "new_identity_btn": "+ New identity",
    "label_work_ph": "Label (e.g. Work)",
    "new_identity": "New identity",
    "identity_created": "Identity created",
    "label_ph": "Label",
    "transfer_code_ph": "Transfer code (haven-seed:…) or seed",
    "link_existing": "Link an existing identity",
    "imported_label": "Imported",
    "imported_toast": "Imported",
    "import_failed": "Import failed: {0}",
    "import": "Import",
    "primary_device_title": "This is your primary device",
    "linked_device_title": "This is a linked device",
    "not_linked_title": "This device isn’t linked yet",
    "primary_device_sub": "It holds your master key and authorizes or revokes your other devices.",
    "linked_device_sub": "It holds a copy of your master key and syncs with your primary device, which can revoke it.",
    "not_linked_sub": "Make it your primary, or link it to the device that already is.",
    "no_devices_linked": "No devices linked yet.",
    "master_key": "Master key",
    "linked_device": "Linked device",
    "revoke_confirm": "Revoke “{0}”? Revoking stops it receiving what you post afterward — which cuts off a device that is simply lost or stolen. It can’t help if someone has extracted your master key from it: linked devices hold a copy of that key, and revoking doesn’t take it back. If that happened, the only remedy is to start a new identity.",
    "revoke": "Revoke",
    "step_down_confirm": "Stop this device acting as the primary?",
    "not_my_primary": "This isn’t my primary",
    "make_my_primary": "Make this my primary",
    "now_primary_toast": "This is now your primary device",
    "asked_primary_toast": "Asked your primary device to authorize this one",
    "resync_primary": "Re-sync from my primary",
    "make_linked_device": "Make this a linked device",
    "add_device_secure": "＋ Add a device (secure link)",
    "new_device": "New device",
    "wants_to_link": "wants to link with a secure code",
    "device_approved": "Device approved — sending its keys",
    "couldnt_create_link_code": "Couldn't create a link code: {0}",
    "enroll_hint": "On the new device choose “Link this as another of my devices” and scan this code (or paste the text). It's single-use and expires in about 10 minutes.",
    "copy_link_code": "Copy link code",
    "link_code_copied": "Link code copied",
    "copy_failed": "Copy failed",
    "enroll_approve_hint": "When the new device asks, come back to Devices and approve it.",
    "add_a_device": "Add a device",
    "missed_call": "Missed call",
    "missed_call_from": "Missed call from {0}",
    "call_media_hairpin": "Call media via fabric tunnel (TCP hairpin)",
    "no_one_to_add": "No one else to add",
    "add_to_call": "Add to call",
    "incoming_call": "Incoming call",
    "is_calling": "{0} is calling…",
    "decline": "Decline",
    "camera_off_suffix": " (camera off)",
    "calling_name": "Calling {0}…",
    "mute": "🎤 Mute",
    "unmute": "🔇 Unmute",
    "camera_off_btn": "📹 Camera off",
    "camera_on_btn": "📷 Camera on",
    "stop_sharing": "🛑 Stop sharing",
    "share_screen": "🖥️ Share screen",
    "add_call_btn": "➕ Add",
    "hang_up": "📞 Hang up",
    "screen_share_unavailable": "Screen share unavailable: {0}",
    "no_screen_selected": "No screen selected",
    "ground_rules": "The ground rules",
    "terms_intro": "Haven is yours and your people's — nobody else can see inside, so keeping it good is on all of us. There is zero tolerance for objectionable content or abusive behavior.",
    "never_allowed_t": "Never allowed",
    "never_allowed_b": "Harassment or bullying, hate, threats or violence, sexual content involving minors, non-consensual intimate content, scams, impersonation, or anything illegal.",
    "enforces_t": "Your circle enforces it",
    "enforces_b": "Anyone can report a post — the whole circle sees the report and can hide it, remove the person, or block them instantly.",
    "on_record_t": "Actions are on the record",
    "on_record_b": "Reports and blocks are logged permanently — who acted against whom and the category, never the content itself. Repeated abuse costs an identity its service.",
    "own_share_t": "You own what you share",
    "own_share_b": "Everything is end-to-end encrypted, so only your circle sees it — and you're responsible for it.",
    "read_full_terms": "Read the full terms of use",
    "i_agree": "I agree",
    "link_move_hint": "On the device you're replacing, open You ▸ Devices ▸ Advanced ▸ Transfer my identity and copy the transfer code. Paste it here. Your identity MOVES — finish setting up here before you retire that device.",
    "link_add_hint": "On your other device open You ▸ Devices ▸ Add a device (secure link) for a one-time code. Paste it here. Both devices stay signed in and stay in sync.",
    "back_arrow": "← Back",
    "paste_link_code_first": "Paste a link code first",
    "couldnt_link": "Couldn't link: {0}",
    "move_account_here": "Move my account here",
    "add_this_device": "Add this device",
    "welcome_haven": "Welcome to Haven",
    "welcome_sub": "A private little place for the people you love.\nNo ads. No tracking. No strangers. Just your people.",
    "new_to_haven_t": "I'm new to Haven",
    "new_to_haven_s": "Create a brand-new identity on this PC.",
    "add_device_choice_t": "Add this as another of my devices",
    "add_device_choice_s": "Use my existing Haven account here too. My other device stays signed in, and both stay in sync.",
    "move_account_t": "Move my account to this device",
    "move_account_s": "Bring my identity over from another device using a transfer code. Use this when replacing a device, not when adding one.",
    "what_call_you": "What should your\npeople call you?",
    "name_nickname_ph": "Your name or nickname",
    "emoji_if_remove_photo": "Emoji (shown if you remove your photo)",
    "or_pick_emoji": "Or pick an emoji",
    "how_haven_works": "How Haven works",
    "private_design_t": "Private by design",
    "private_design_b": "Everything you share is locked so only the people in your circle can ever see it.",
    "no_ads_t": "No ads, no tracking",
    "no_ads_b": "There's no algorithm and no company watching. Haven doesn't collect anything about you.",
    "choose_circle_t": "You choose your circle",
    "choose_circle_b": "Nothing happens with strangers. You invite the people you want, one at a time.",
    "couldnt_create": "Couldn't create: {0}",
    "i_agree_enter": "I agree — enter Haven",
    "continue_btn": "Continue",
    "no_phone_email": "No phone number. No email. Your keys never leave this device.",
    "waiting_other_device": "Waiting for your other device",
    "seedless_hint": "Open Haven on the device that has your account, go to You ▸ Devices, and approve this device. It'll get its own key — your master seed never leaves that device.",
    "check_again": "Check again",
    "backend_not_ready": "Backend not ready: {0}",
    "fabric_ready": "Haven fabric ready — reconnecting this session onto circle DERP…",
    "fabric_connected": "Connected on Haven fabric (circle DERP)",
    "device_wants_link": "“{0}” wants to link — open You ▸ Devices to approve",
    "feedback_support": "Feedback & Support",
    "report_issue": "Report an Issue",
    "suggest_feature": "Suggest a Feature",
    "ask_question": "Ask a Question",
    "support_foot": "I can't fix what I don't know about. If something is broken, confusing, or missing, email me — one person reads every message, and a fix for you is a fix for everyone.",
    "my_other_apps": "My Other Apps",
    "other_apps_sub": "Built by one person, same care",
    "bug_report": "Bug Report",
    "feature_request": "Feature Request",
    "question": "Question",
    "fb_bug_template": "Hi Blaine,\n\nI ran into a problem with {0}.\n\nWhat went wrong:\n\n\nSteps to reproduce:\n1.\n2.\n3.\n\nWhat I expected to happen:\n\n\nHow often it happens (always / sometimes / once):\n",
    "fb_feature_template": "Hi Blaine,\n\nI have an idea for {0}.\n\nWhat I'd like to be able to do:\n\n\nWhy it would help / the problem it solves:\n\n\nHow I imagine it working:\n",
    "fb_question_template": "Hi Blaine,\n\nI have a question about {0}.\n\nWhat I'm trying to do:\n\n\nWhat I've tried so far:\n",
    "improve_translation": "Improve the {0} translation",
    "tf_intro": "This app was translated into {0} with machine help, and machine help only gets it so far. If something reads wrong, stiff, or just isn't how anyone actually says it — you're the only person who can tell me.",
    "before_we_start": "Before we start",
    "reads_english": "I read and write English comfortably",
    "will_iterate": "I'm happy to go back and forth on the wording",
    "tf_gate_foot": "I only speak English, so getting a translation right means a few messages back and forth. If that isn't something you want to do, please still report it as a normal issue — I'd rather know than not.",
    "what_needs_fixing": "What needs fixing",
    "tf_screen_ph": "e.g. Settings screen, the Save button",
    "tf_current_ph": "Paste or type what it says now",
    "tf_suggested_ph": "What it should say in {0}",
    "tf_notes_ph": "Anything else worth knowing (optional)",
    "send_it": "Send it to me",
    "tf_send_foot": "This opens your mail app so you can see exactly what's being sent. Nothing leaves your device until you hit send.",
    "tf_body_intro": "Hi Blaine,\n\nI'd like to help improve the {0} translation in {1}.\n",
    "where_in_app": "Where in the app:",
    "says_now": "What it says now:",
    "should_say": "What it should say:",
    "why_else": "Why / anything else:",
    "tf_confirm_line": "I read and write English comfortably, and I'm happy to go back and forth until the wording is right.",
    "displaying": "Displaying:",
  };

  const T = {
    "ja": {

    },
    "de": {

    },
    "es": {

    },
    "ko": {

    },
    "pt-BR": {

    },
    "it": {

    },
  };

  // pt-BR is matched specially; every other supported language matches on its 2-letter primary
  // subtag. Anything else — including plain pt/pt-PT, fr and zh — falls back to English.
  function pickLang() {
    const raw = String((typeof navigator !== "undefined" && navigator.language) || "en");
    if (/^pt[-_]?br/i.test(raw)) return "pt-BR";
    const primary = raw.slice(0, 2).toLowerCase();
    return ["ja", "de", "es", "ko", "it"].indexOf(primary) >= 0 ? primary : "en";
  }

  const LANG = pickLang();
  const ACTIVE = T[LANG] || {};

  function format(s, args) {
    if (!args.length) return s;
    return s.replace(/\{(\d+)\}/g, (m, i) => (args[i] === undefined ? m : String(args[i])));
  }

  /** Translated string for key, English fallback, {0}/{1} placeholder substitution. */
  function t(key) {
    const args = Array.prototype.slice.call(arguments, 1);
    const s = ACTIVE[key] !== undefined ? ACTIVE[key] : (EN[key] !== undefined ? EN[key] : key);
    return format(s, args);
  }

  /** The ENGLISH string for key — for values that ride the wire (e.g. report reasons), where the
   *  circle's other members must see the same canonical text every client sends. */
  function tEn(key) {
    const args = Array.prototype.slice.call(arguments, 1);
    return format(EN[key] !== undefined ? EN[key] : key, args);
  }

  /** Replace the FIRST text node so children (badges, icons) survive — the tab buttons carry a
   *  badge <i> after their label. */
  function setFirstText(elm, s) {
    for (let i = 0; i < elm.childNodes.length; i++) {
      const n = elm.childNodes[i];
      if (n.nodeType === 3) { n.nodeValue = s; return; }
    }
    elm.insertBefore(document.createTextNode(s), elm.firstChild);
  }

  /** Apply data-i18n / data-i18n-title / data-i18n-aria / data-i18n-placeholder attributes in
   *  index.html's static markup. Runs once at load; app.js renders everything else through t(). */
  function applyTranslations(root) {
    const scope = root || document;
    scope.querySelectorAll("[data-i18n]").forEach((n) => setFirstText(n, t(n.getAttribute("data-i18n"))));
    scope.querySelectorAll("[data-i18n-title]").forEach((n) => n.setAttribute("title", t(n.getAttribute("data-i18n-title"))));
    scope.querySelectorAll("[data-i18n-aria]").forEach((n) => n.setAttribute("aria-label", t(n.getAttribute("data-i18n-aria"))));
    scope.querySelectorAll("[data-i18n-placeholder]").forEach((n) => n.setAttribute("placeholder", t(n.getAttribute("data-i18n-placeholder"))));
  }

  window.t = t;
  window.tEn = tEn;
  window.HAVEN_LANG = LANG;
  window.HAVEN_STRINGS_EN = EN;
  window.applyTranslations = applyTranslations;

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () { applyTranslations(); });
  } else {
    applyTranslations();
  }
})();
